"""empty message

Revision ID: 25006342bcd3
Revises: fd9318765ace
Create Date: 2024-10-30 20:58:35.858164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25006342bcd3'
down_revision = 'fd9318765ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
